# pre-commit install --allow-missing-config
---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.11.0
    hooks:
      - id: yamllint
        args: [
          '-d',
          '{extends: relaxed, rules: {line-length: {max: 120}}}'
        ]
  - repo: git://github.com/dnephin/pre-commit-golang
    sha: v0.3.3
    hooks:
      - id: go-fmt
      - id: go-unit-tests
      - id: go-build
  - repo: https://github.com/troian/pre-commit-golang
    sha: HEAD
    hooks:
      - id: go-fmt
